name: archeryozs
description: "A new Flutter project."
publish_to: 'none'

# version: 1.0.0+1
version: 0.1.0-dev

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  go_router: ^13.2.0
  flutter_secure_storage: ^9.0.0
  flutter_web_auth_2: ^2.2.1
  cupertino_icons: ^1.0.8
  google_sign_in: ^5.2.1
  image_picker: ^1.0.7
  transparent_image: ^2.0.1
  flutter_localizations:
    sdk: flutter
  intl_phone_number_input: ^0.7.3
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.66.2
  uuid: ^4.5.1
  connectivity_plus: ^5.0.2
  sqflite: ^2.4.1
  brick_sqlite: ^4.0.1
  intl: ^0.19.0
  provider: ^6.1.5
  cached_network_image: ^3.3.1
  just_audio: ^0.9.46
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.10
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

flutter_intl:
  enabled: true
  main_locale: tr
  output_dir: lib/generated

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/archeryozslogo_2.png"
